In [0]:
import numpy as np
from scipy import signal
from scipy import misc

In [4]:
#1D CONV
x = np.array([0,1,2,3,4])
w = np.array([1,-1,2])

print('x = ',x)
print('w = ',w)

res = np.convolve(x,w)
print('conv(x,w) = ',res)

x =  [0 1 2 3 4]
w =  [ 1 -1  2]
conv(x,w) =  [0 1 1 3 5 2 8]


In [9]:
x1 = np.array([8,4,2,6,4,10])
w1 = np.array([9,-10,2,-9])

print('x1 = ',x1)
print('w1 = ',w1)

res1 = np.convolve(x1,w1)
print('conv(x1,w1) = ',res1)

x1 =  [ 8  4  2  6  4 10]
w1 =  [  9 -10   2  -9]
conv(x1,w1) =  [  72  -44   -6  -30  -56   44 -146  -16  -90]


In [11]:
#2D CONV
x = np.array([[1,2,0],[4,1,1],[3,1,2]])
w = np.array([[2,2],[1,-1]])
           
print('x = \n',x)
print('w = \n',w)
             
res1 = signal.convolve2d(x,w,'valid')
res2 = signal.convolve2d(x,w,'same')
res3 = signal.convolve2d(x,w,'full')

print('\n valid conv_2d(x,w) = \n', res1)
print('\n same conv_2d(x,w) = \n', res2)
print('\n full conv_2d(x,w) = \n', res3)

x = 
 [[1 2 0]
 [4 1 1]
 [3 1 2]]
w = 
 [[ 2  2]
 [ 1 -1]]

 valid conv_2d(x,w) = 
 [[11  2]
 [ 5  6]]

 same conv_2d(x,w) = 
 [[ 2  6  4]
 [ 9 11  2]
 [10  5  6]]

 full conv_2d(x,w) = 
 [[ 2  6  4  0]
 [ 9 11  2  2]
 [10  5  6  3]
 [ 3 -2  1 -2]]


In [13]:
#EX1
x = np.array([[1,0,2],[1,1,-1],[2,0,2]])
w = np.array([[1,-1],[0,2]])
           
print('x = \n',x)
print('w = \n',w)

res1 = signal.convolve2d(x,w,'valid')
print('\n valid conv_2d(x,w) = \n', res1)

x = 
 [[ 1  0  2]
 [ 1  1 -1]
 [ 2  0  2]]
w = 
 [[ 1 -1]
 [ 0  2]]

 valid conv_2d(x,w) = 
 [[ 2 -2]
 [ 0  4]]


In [14]:
#EX2
x = np.array([[1,1,2,0],[-1,0,1,1],[2,1,-1,0],[1,0,1,2]])
w = np.array([[0,2],[-1,3]])
           
print('x = \n',x)
print('w = \n',w)

res1 = signal.convolve2d(x,w,'valid')
print('\n valid conv_2d(x,w) = \n', res1)

x = 
 [[ 1  1  2  0]
 [-1  0  1  1]
 [ 2  1 -1  0]
 [ 1  0  1  2]]
w = 
 [[ 0  2]
 [-1  3]]

 valid conv_2d(x,w) = 
 [[ 0  1  8]
 [ 1  1  0]
 [ 7  4 -1]]
